import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { dummyEvents } from "~/events";
import { formatDateTime } from "~/util/formateDateTime";
import { useRef, useEffect } from "react";
import { useRouter } from "next/router";

export default function EventsId() {
  const router = useRouter();
  const buttonRef = useRef(null);

  useEffect(() => {
    const handleScroll = () => {
      if (buttonRef.current) {
        const rect = buttonRef.current.getBoundingClientRect();
        if (rect.top <= 0) {
          buttonRef.current.classList.add("top-0");
          buttonRef.current.classList.add("bg-gradient-to-b");
          buttonRef.current.classList.add("from-transparent");
          buttonRef.current.classList.add("to-black");
          buttonRef.current.classList.add("to-black");
        } else {
          buttonRef.current.classList.remove("top-0");
          buttonRef.current.classList.remove("bg-gradient-to-b");
          buttonRef.current.classList.remove("from-transparent");
          buttonRef.current.classList.remove("to-black");
          buttonRef.current.classList.remove("to-black");
        }
      }
    };

    window.addEventListener("scroll", handleScroll);

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  if (!router.isReady) return null;

  const id: number = router.query.eventsId;

  const formattedDateTime = formatDateTime(
    dummyEvents[id]!.date,
    dummyEvents[id]!.time,
  );

  return (
    <>
      <Head>
        <title>Live</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="to flex min-h-screen flex-col w-screen bg-gradient-to-b from-[#2e026d] to-[black] py-16 px-16">
        <div className="flex flex-col gap-12">
          <Image
            src={dummyEvents[id]!.carouselImages[1]}
            alt="1"
            width={500}
            height={500}
            style={{
              width: "100%",
              height: "100%",
            }}
          />
          <div
            ref={buttonRef}
            className="sticky top-0 z-50 flex justify-between  py-5 "
          >
            <div className="flex flex-col gap-5">
              <h1 className="text-2xl font-extrabold tracking-tight text-white sm:text-[3rem]">
                {dummyEvents[id]!.title}
              </h1>
              <h3 className="text-sm font-extrabold tracking-tight text-white md:text-[1rem]">
                {formattedDateTime.date} at {formattedDateTime.time}
              </h3>
            </div>
            <Link href={`/events/${id}/ticket`}>
                <button className="  rounded-lg bg-yellow-500 px-8 py-4 text-l font-bold text-white transition duration-150 ease-in-out hover:bg-yellow-600 focus:outline-none ">
                  <div className=" border-b-2 border-dashed "></div>
                  Buy Ticket
                  <div className=" border-b-2 border-dashed"></div>
                </button>
              </Link>
          </div>
          <h3 className="text-2xl font-extrabold tracking-tight text-white underline sm:text-[2rem]">
            Description
          </h3>
          <div className="w-1/2 border border-gray-500 p-5 text-center text-lg text-white">
            {dummyEvents[id]!.description}
          </div>
 
          <div className="text-lg text-white">
            {dummyEvents[id]!.location}
            <div className="relative h-[200px] w-[100%]">
              <iframe
                src={`http://maps.google.com/maps?q=${
                  dummyEvents[id]!.latitude
                },${dummyEvents[id]!.longitude}&z=16&output=embed`}
                width="100%"
                height="200"
                loading="lazy"
                className=""
              ></iframe>
              <div className="item absolute inset-0 flex justify-center bg-gradient-to-t from-purple-300 to-transparent opacity-70 hover:opacity-90">
                <Link
                  href={`http://maps.google.com/maps?q=${
                    dummyEvents[id]!.latitude
                  },${dummyEvents[id]!.longitude}`}
                >
                  <div className="flex h-full w-full items-center align-middle font-extrabold text-black opacity-0 hover:opacity-100">
                    {" "}
                    Open in google maps
                  </div>
                </Link>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
