import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

export default function Events() {
  return (
    <>
      <Head>
        <title>Live</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[black]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <Image
            src="https://media.graphassets.com/DP1k7torQLWW2PJRDh7n"
            alt="1"
            width={500}
            height={500}
            style={{
              width: "100vw",
              height: "100%",
            }}
          />

          <h1 className="text-2xl font-extrabold tracking-tight text-white sm:text-[3rem]">
            Coldplay Concert 2023
          </h1>

          <h3 className="text-2xl font-extrabold tracking-tight text-white underline sm:text-[2rem]">
            Description
          </h3>
          <div className="w-5/6 border border-gray-500 p-5 text-lg text-white">
            Coldplay back to Indonesia with their new album `Music of the
            Spheres`! , Coldplay will held their concert in Jakarta, Indonesia
            on 20 November 2023. Don`t miss it!
          </div>

          <h3 className="text-2xl font-extrabold tracking-tight text-white underline sm:text-[2rem]">
            Date and Time
          </h3>
          <h3 className="text-1xl font-extrabold tracking-tight text-white sm:text-[2rem]">
            Saturday, 20 November 2023
          </h3>

          <h3 className="text-2xl font-extrabold tracking-tight text-white underline sm:text-[2rem]">
            Location
          </h3>
          <div className="text-lg text-white">
            Jakarta International Expo, Kemayoran, Jakarta Pusat
            <div className="relative h-[200px] w-[100%]">
              <iframe
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3966.8828337813175!2d106.84266107565821!3d-6.146435293840595!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e69f59269e62e3d%3A0xb3da35d58f3f6382!2sJakarta%20International%20Expo%2C%20RW.10%2C%20East%20Pademangan%2C%20Pademangan%2C%20Central%20Jakarta%20City%2C%20Jakarta%2014410!5e0!3m2!1sen!2sid!4v1695194287602!5m2!1sen!2sid"
                width="100%"
                height="200"
                loading="lazy"
                className=""
              ></iframe>
              <div className="item absolute inset-0 flex justify-center bg-gradient-to-t from-purple-300 to-transparent opacity-70 hover:opacity-90">
                <button className="h-full w-full text-black opacity-0 hover:opacity-100">
                  Open in google maps
                </button>
              </div>
            </div>
          </div>
          <h3 className="text-2xl font-extrabold tracking-tight text-white underline sm:text-[2rem]">
            Price
          </h3>
          <div className="text-lg text-white">Rp 1.000.000 - Rp 5.000.000</div>
          <h3 className="text-2xl font-extrabold tracking-tight text-white underline sm:text-[2rem]">
            Join The War
          </h3>
          <Link href="/events/1/ticket">
            <button className="relative rounded-lg bg-yellow-500 px-8 py-4 text-xl font-bold text-white transition duration-150 ease-in-out hover:bg-yellow-600 focus:outline-none ">
              <div className=" border-b border-b-2 border-dashed ">
                <div className="absolute -left-2 -mt-7 h-5 w-5 rounded-full bg-black "></div>
                <div className="absolute -right-2 -mt-7 h-5 w-5 rounded-full bg-black"></div>
              </div>
              Buy Ticket
              <div className="border-b border-b-2 border-dashed">
                <div className="absolute -left-2 mt-2 h-5 w-5 rounded-full bg-black"></div>
                <div className="absolute -right-2 mt-2 h-5 w-5 rounded-full bg-black"></div>
              </div>  
            </button>
          </Link>
        </div>
      </main>
    </>
  );
}
