import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

export default function Events() {
  const tickets = [
    {
      id: 1,
      name: "Cat 1",
      price: 100000,
      qty: 100,
      color: "yellow",
      outOfStock: false,
    },
    {
      id: 2,
      name: "Cat 2",
      price: 80000,
      qty: 100,
      color: "green",
      outOfStock: false,
    },
    {
      id: 3,
      name: "Cat 3",
      price: 60000,
      qty: 100,
      color: "blue",
      outOfStock: true,
    },
    {
      id: 4,
      name: "Cat 4",
      price: 40000,
      qty: 100,
      color: "red",
      outOfStock: false,
    },
    {
      id: 5,
      name: "Cat 5",
      price: 20000,
      qty: 100,
      color: "purple",
      outOfStock: false,
    },
  ];
  return (
    <>
      <Head>
        <title>Live</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[black] ">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">

          <Image
            src={
              "https://awsimages.detik.net.id/community/media/visual/2023/05/11/harga-tiket-konser-coldplay-jakarta-2023.jpeg?w=1080"
            }
            alt="1"
            width={750}
            height={750}
            style={{ width: "90vw", height: "100%" }}
          />
          <h1 className="text-2xl font-extrabold tracking-tight text-white sm:text-[3rem]">
            Select Your Category
          </h1>
          <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4">
          {tickets.map((ticket) => (
        <Link href="/home/events/live/1" key={ticket.id}>
            <button
                className={`relative rounded-lg bg-${ticket.color}-500 m-3 px-8 py-4 text-xl font-bold text-white transition duration-150 ease-in-out hover:bg-yellow-600 focus:outline-none disabled:cursor-not-allowed disabled:bg-gray-400 disabled:text-gray-300 position-relative`}
                disabled={ticket.outOfStock}
            >
                <div className="border-b-2 border-dashed"></div>
                {ticket.outOfStock && <span className="z-10 text-sm absolute transform -translate-x-1/2 text-red-500 font-bold rotate-[-17deg] bg-white border-2 border-red-500">Out Of Stock</span>}
                <p className="z-0">{ticket.name}</p>
                <p className="z-0">Rp. {ticket.price}</p>
                <div className="border-b-2 border-dashed"></div>
            </button>
        </Link>
    ))}
          
          </div>
        </div>
      </main>
    </>
  );
}
