import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { useRouter } from "next/router";
import { dummyEvents } from "~/events";

export default function Events() {

const router = useRouter();
const id: number = router.query.eventsId;

  return (
    <>
      <Head>
        <title>Live</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[black] ">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">

          <Image
            src={
              "https://awsimages.detik.net.id/community/media/visual/2023/05/11/harga-tiket-konser-coldplay-jakarta-2023.jpeg?w=1080"
            }
            alt="1"
            width={750}
            height={750}
            style={{ width: "80vh"}}
          />
          <h1 className="text-2xl font-extrabold tracking-tight text-white sm:text-[3rem]">
            Select Your Category
          </h1>
          <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4">
          {dummyEvents[id]?.ticketTypes.map((ticket) => (
        <Link href="/home/events/live/1" key={ticket.id}>
            <button
                className={`relative rounded-lg bg-${ticket.color}-500 m-3 px-8 py-4 text-xl font-bold text-white transition duration-150 ease-in-out hover:bg-${ticket.color}-400 focus:outline-none disabled:cursor-not-allowed disabled:bg-gray-400 disabled:text-gray-300 position-relative`}
                disabled={ticket.availableSeats === 0}
            >
                <div className="border-b-2 border-dashed"></div>
                {ticket.availableSeats===0 && <span className="z-10 text-sm absolute transform -translate-x-1/2 text-red-500 font-bold rotate-[-17deg] bg-white border-2 border-red-500">Out Of Stock</span>}
                <p className="z-0">{ticket.type}</p>
                <p className="z-0">Rp. {ticket.price}</p>
                <div className="border-b-2 border-dashed"></div>
            </button>
        </Link>
    ))}
          
          </div>
        </div>
      </main>
    </>
  );
}
