import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

export default function Events() {
  return (
    <>
      <Head>
        <title>Live</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[black] ">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">

          <Image
            src={
              "https://awsimages.detik.net.id/community/media/visual/2023/05/11/harga-tiket-konser-coldplay-jakarta-2023.jpeg?w=1080"
            }
            alt="1"
            width={200}
            height={200}
            style={{ width: "90vw", height: "100%" }}
          />
          <h1 className="text-2xl font-extrabold tracking-tight text-white sm:text-[3rem]">
            Select Your Category
          </h1>
          <div className="grid grid-cols-1 sm:grid-cols-2">
            <Link href="/home/events/live/1/checkout" className="m-3">
              <button className="w- relative rounded-lg bg-blue-800  px-8 py-4 text-xl font-bold text-white transition duration-150 ease-in-out hover:opacity-80 focus:outline-none">
                <div className=" border-b border-b-2 border-dashed ">
                  Cat 1
                  <div className="absolute -left-2 -mt-14 h-5 w-5 rounded-full bg-black "></div>
                  <div className="absolute -right-2 -mt-14 h-5 w-5 rounded-full bg-black"></div>
                </div>
                Rp. 1.000.000
                <div className="border-b border-b-2 border-dashed">
                  <div className="absolute -left-2 mt-7 h-5 w-5 rounded-full bg-black"></div>
                  <div className="absolute -right-2 mt-7 h-5 w-5 rounded-full bg-black"></div>
                </div>
                <div className="mini-ticket-description text-sm">
                  {" "}
                  Cannot be refunded, Seat Automatically Choosen, 2 Days Pass
                </div>
              </button>
            </Link>
            <Link href="/events/1/ticket/checkout/1" className="m-3">
              <button className="w- relative w-full rounded-lg bg-orange-500 px-8 py-4 text-xl font-bold text-white transition duration-150 ease-in-out hover:opacity-90 hover:text-white focus:outline-none">
                <div className=" border-b border-b-2 border-dashed">
                  Cat 2
                  <div className="absolute -left-2 -mt-14 h-5 w-5 rounded-full bg-black "></div>
                  <div className="absolute -right-2 -mt-14 h-5 w-5 rounded-full bg-black"></div>
                </div>
                Rp. 1.000.000
                <div className="border-b border-b-2 border-dashed">
                  <div className="absolute -left-2 mt-7 h-5 w-5 rounded-full bg-black"></div>
                  <div className="absolute -right-2 mt-7 h-5 w-5 rounded-full bg-black"></div>
                </div>
                <div className="mini-ticket-description text-sm">
                  {" "}
                  Cannot be refunded,{" "}
                </div>
              </button>
            </Link>
            <Link href="#" className="m-3">
              <button disabled className="w- relative w-full rounded-lg bg-white px-8 py-4 text-xl font-bold text-black transition duration-150 ease-in-out hover:bg-gray-600 hover:text-white focus:outline-none disabled:bg-gray-200 disabled:text-gray-500 disabled:cursor-not-allowed">
               
                <div className=" border-b border-b-2 border-dashed ">
                  
                  Cat 3
                  <div className="absolute -left-2 -mt-14 h-5 w-5 rounded-full bg-black "></div>
                  <div className="absolute -right-2 -mt-14 h-5 w-5 rounded-full bg-black"></div>
                  <h1 className="text-red-500 ">Sold out</h1>
                </div>
                Rp. 1.000.000
                <div className="border-b border-b-2 border-dashed">
                  <div className="absolute -left-2 mt-7 h-5 w-5 rounded-full bg-black"></div>
                  <div className="absolute -right-2 mt-7 h-5 w-5 rounded-full bg-black"></div>
                </div>
                <div className="mini-ticket-description  text-sm">
                  {" "}
                  Cannot be refunded,{" "}
                </div>
              </button>
            </Link>
          
          </div>
        </div>
      </main>
    </>
  );
}
