import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-4xl font-extrabold tracking-tight text-white sm:text-[4rem]">
            Looking for  <span className="text-[hsl(280,100%,70%)]">Ticketing War</span> Platform?
          </h1>
          <div className="flex w-screen items-center justify-center">
    <div className="w-1/2 flex items-center justify-end">
    <input className="w-full h-10 rounded-full p-5" placeholder="Coldplay Ticket..."></input>
    <button className="absolute p-3 text-indigo">Search</button>
    </div>
</div>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/login"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">As User</h3>
              <div className="text-lg">
                Join The War and get your ticket right now!
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/register"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">As Seller →</h3>
              <div className="text-lg">
                Create a memorable war and make it big!
              </div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
