import Head from "next/head";
import Link from "next/link";

export default function Login() {
    const revealPass = () => {
        const pass = document.querySelector('#password');
        const reveal = document.querySelector('#reveal')!;
        if (pass?.getAttribute('type') === 'password') {
            pass.setAttribute('type', 'text')
            reveal.innerHTML = 'Hide'
            console.log('reveal')
        } else {
            pass?.setAttribute('type', 'password')
            reveal.innerHTML = 'Reveal'
            console.log('hide')
        }
    }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-3xl font-extrabold tracking-tight text-white sm:text-[4rem]">
            Login
          </h1>
          <h2 className="text-white">
            Welcome back!
          </h2>
       

          <div className="grid md:gap-8 md:w-1/2 sm:w-fullx">
            <div
              className="flex w-full flex-col gap-4 rounded-xl bg-white/10 p-4 text-white"
            >
              <h3 className="text-xl font-bold">Email</h3>
              <input className="text-black w-full rounded-md p-2 border-2 hover:border-blue-200 focus:border-blue-400"></input>
              <h3 className="text-xl font-bold">Password</h3>
              <div className="w-full flex items-center justify-end">
              <input id="password" type="password" className="text-black w-full rounded-md p-2 border-2 hover:border-blue-200 focus:border-blue-400"></input>
    <button id="reveal" className="absolute p-3 text-indigo text-black" onClick={revealPass}>Reveal</button>
    </div>
              <button className="hover:bg-white/20 w-full">Login</button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
