import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-4xl font-extrabold tracking-tight text-white sm:text-[4rem]">
            On Going
          </h1>
          <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/events/1"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Coldplay Ticket</h3>
              <div className="text-lg">
                Join The War and get your ticket right now!
              </div>
            </Link>

        </div>
          <div className="flex w-screen items-center justify-center">
    <div className="w-1/2 flex items-center justify-end">
    <input className="w-full h-10 rounded-full p-5" placeholder="Coldplay Ticket..."></input>
    <button className="absolute p-3 text-indigo">Search</button>
    </div>
</div>

<div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
<h1 className="text-4xl font-extrabold tracking-tight text-white sm:text-[4rem]">
            Upcoming
          </h1>
<div className="grid grid-cols-1 gap-4 sm:grid-cols-4 md:gap-8 mt-5">
    
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/register"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Fuji Kaze</h3>
              <div className="text-lg">
                Japanese Singer and Songwriter Fuji Kaze is coming to Indonesia!
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/register"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Alan Walker</h3>
              <div className="text-lg">
                Alan Walker is coming to Indonesia!
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/register"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Billie Elish</h3>
              <div className="text-lg">
                Billie Elish is coming to Indonesia!
              </div>
              </Link>
              <Link
                className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/register"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Elvis Presley</h3>
              <div className="text-lg">
                Elvis Presley is coming to Indonesia!
              </div>
            </Link>
          </div>

        </div>



      </main>
    </>
  );
}
